### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by ChaseNelson** [ChaseNelson/cs252-Web-App#3]
Users should be able to make message posts on their page. These messages are just text messages.

They should be stored in the database under a message section that is headed by a uid (A) the contains all of (A)s messages and each messages info.

**Comment by pfortunato** [comment]
Works but is unsorted

**Comment by ChaseNelson** [comment]
making new posts will crash the server.
```
Error: Can't set headers after they are sent.
```
Maybe try getting the messages from firebase client side to avoid this error.
